name: run main.py daily

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 14 * * *'  # runs at 2pm UTC daily

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: lint main.py
        run: |
          flake8 main.py || echo "flake8 issues found, continuing anyway"

      - name: run script
        run: |
          python main.py
